[package]
name = "geo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.28"
wkt = "0.10"
csv = "1.3"
proj = "0.27"
