[package]
name = "graphs"
version = "0.1.0"
edition = "2021"

[dependencies]
graph = "0.3.1"
log = "0.4.19"
polars = { version = "0.25.1", default_features = false, features = ["fmt"] }
env_logger = "0.9.3"
